POST http://localhost:9080/register HTTP/1.1
Content-Type: application/json

{
  "username": "john_doe_31",
  "password": "securePassword123",
  "email": "john31@example.com",
  "name": "John Doe"

}
###
POST http://localhost:9080/login
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john31@example.com",
  "password": "securePassword123",
  "username": "john_doe_31"

}
###
GET http://localhost:9080/get_user_and_profile?token=ed7b8f6ab6c5e37a2069d3c66ee15a7f6ab1bd7b093289e77854a6f73324665f



###
### Update Profile Data
POST http://localhost:9080/update_profile_data
Content-Type: application/json

{
  "token": "79352894958e44ce87df6e75ed2756881ae5ce5b1414f396cab5956351a25b2b",
  "bio": "Hey i am neha",
  "currentPost": "CTO",
  "pastWork": [
    {
      "company": "Microsoft",
      "position": "CTO",
      "years": "2+"
    }
  ],
  "education": [
    {
      "school": "IIIT",
      "degree": "BCA",
      "fieldOfStudy": "2015-2019"
    }
  ]
}
### Get all user profiles
GET http://localhost:9080/user/get_all_users
